### ISSUE TITLE
Overide default webhook channel

### ISSUE THREAD

**Issue by molteninjabob** [jackcoded/newman-reporter-slackmsg#4]
The Slack webhook provides the ability to override the default channel. We are setting up newman to run a dynamic set of folders based on the service running the tests and we want to alert different team channels with the results. It would be great to be able to override the default.

https://getweave.slack.com/services/B01C28M8EKA?added=1

Channel Override
Incoming webhooks have a default channel, but it can be overridden in your JSON payload. A public channel can be specified with "channel": "#other-channel", and a Direct Message with "channel": "@username".

**Comment by jackcoded** [comment]
Could go into more details about channel override and that slack provides the ability to override the default channel?

**Comment by molteninjabob** [comment]
In the JSON payload you are sending to the webhook URL, you can specify a public channel to post the message to, which overrides the default channel set for the incoming webhook. The image below was taken from the webhook configuration page.

![Incoming WebHooks | Slack App Directory 2020-10-05 11-47-11](https://user-images.githubusercontent.com/11509961/95114053-953b0680-0700-11eb-9195-56cb0e00bd3d.jpg)

I think all that would need to be done is to accept a channel parameter and add it to the payload you are creating in the send function in slackUtils.js

`// sends the message to slack via POST to webhook url
async function send(slackHookUrl, message, channel) {
    const payload = {
        method: 'POST',
        url: slackHookUrl,
        data: message,
        headers: {
            'content-type': 'application/json',
        },
        channel: channel,
    };`

**Comment by jackcoded** [comment]
Ahh i see, i'll try to work on it when i'm free.

**Comment by molteninjabob** [comment]
Awesome! Thank you! If I get any free time, I might try to submit a pull request, but this is a pretty busy week. Appreciate you putting this tool together!

**Comment by jackcoded** [comment]
I should be nearly done with the changes last night, will hopefully finish by tomorrow. Also being smashed by work and late night support work. Make sure you star this repository if you liked it.

**Comment by jackcoded** [comment]
Never mind, i just finished it now. Hopefully it works well and any problems you can create another issue.

**Comment by molteninjabob** [comment]
Thanks for jumping on this so quickly! 

Just for clarification, I see that you changed the incoming webhook url to take a token instead and the readme says to set up a bot. The Bot requires you to set up permissions and has an option for both incoming-webhook and chat:write. I've never set up a slack app before; do you know specifically which permissions are needed? Also, if we add incoming-webhook to the bot, will that replace the incoming-webhook already set up? Some clarification around this added to the README would be helpful.

But so glad to have this option now. Thank you again!

**Comment by jackcoded** [comment]
Hi, this resource should be good for creating a bot and using it to send message to the channel.
[https://api.slack.com/messaging/sending](url)
About your incoming webhook, you wouldn't need it anymore as you can dynamically just select channel by giving the channel name to the input. But i assume it will change the webhook url.

Here's a quick overview on how to set up and use it
The required permission for bot is **channels:read** and **chat:write:bot**
After creating the bot with the permission you need the Bot OAuth Bearer token 
Then go to your channel -> add Apps -> select your bot and install it
To use the bot for message for the changes it would be using **https://slack.com/api/chat.postMessage** as the webhook url instead of the static webhook.

 newman run <collectionFile> -e <environmentFile> --suppress-exit-code -r slackmsg --reporter-slackmsg-webhookurl '<https://slack.com/api/chat.postMessage>' --reporter-slackmsg-token '<bearer token>' --reporter-slackmsg-chanel '<channel or userid>'

**Comment by molteninjabob** [comment]
This is perfect, thank you! I'm waiting for org. approval to install the bot, but as soon as it comes through, I'll test it and let you know.
